

export const RequestedLeave = [
    {
      employeeId: 1,
      firstName: 'John',
      lastName: 'Doe',
      availableSickLv: 5,
      availableAnnualLv: 10,
      email: 'john.doe@example.com',
      availableLv: 15,
      reason: 'Vacation',
      hoursOfLvRequested: 40,
      typeofLv: 'Annual Leave',
      lvStartDate: '2023-07-01',
      lvEndDate: '2023-07-10',
      status: 'Approved'
    },
    {
      employeeId: 2,
      firstName: 'Jane',
      lastName: 'Smith',
      availableSickLv: 3,
      availableAnnualLv: 8,
      email: 'jane.smith@example.com',
      availableLv: 11,
      reason: 'Medical',
      hoursOfLvRequested: 24,
      typeofLv: 'Sick',
      lvStartDate: '2023-08-05',
      lvEndDate: '2023-08-08',
      status: 'Pending'
    },
    {
      employeeId: 444,
      firstName: 'Alice',
      lastName: 'Johnson',
      availableSickLv: 6,
      availableAnnualLv: 7,
      email: 'alice.johnson@example.com',
      availableLv: 13,
      reason: 'Family',
      hoursOfLvRequested: 32,
      typeofLv: 'Military',
      lvStartDate: '2023-09-10',
      lvEndDate: '2023-09-15',
      status: 'Denied'
    },
    {
      employeeId: 564,
      firstName: 'Bob',
      lastName: 'Brown',
      availableSickLv: 4,
      availableAnnualLv: 9,
      email: 'bob.brown@example.com',
      availableLv: 13,
      reason: 'Court',
      hoursOfLvRequested: 16,
      typeofLv: 'Jury Duty',
      lvStartDate: '2023-10-01',
      lvEndDate: '2023-10-03',
      status: 'Canceled'
    },
    {
      employeeId: 465,
      firstName: 'Charlie',
      lastName: 'Davis',
      availableSickLv: 5,
      availableAnnualLv: 12,
      email: 'charlie.davis@example.com',
      availableLv: 17,
      reason: 'Holiday',
      hoursOfLvRequested: 40,
      typeofLv: 'Admin',
      lvStartDate: '2023-11-20',
      lvEndDate: '2023-11-27',
      status: 'Approved'
    },
    {
      employeeId: 5473,
      firstName: 'Eva',
      lastName: 'Green',
      availableSickLv: 2,
      availableAnnualLv: 10,
      email: 'eva.green@example.com',
      availableLv: 12,
      reason: 'Medical',
      hoursOfLvRequested: 24,
      typeofLv: 'Sick',
      lvStartDate: '2023-12-05',
      lvEndDate: '2023-12-08',
      status: 'Denied'
    },
    {
      employeeId: 237,
      firstName: 'Frank',
      lastName: 'Harris',
      availableSickLv: 8,
      availableAnnualLv: 10,
      email: 'frank.harris@example.com',
      availableLv: 18,
      reason: 'Family',
      hoursOfLvRequested: 32,
      typeofLv: 'Military',
      lvStartDate: '2024-01-10',
      lvEndDate: '2024-01-15',
      status: 'Canceled'
    },
    {
      employeeId:874,
      firstName: 'Grace',
      lastName: 'King',
      availableSickLv: 7,
      availableAnnualLv: 12,
      email: 'grace.king@example.com',
      availableLv: 19,
      reason: 'Jury Duty',
      hoursOfLvRequested: 16,
      typeofLv: 'Jury Duty',
      lvStartDate: '2024-02-15',
      lvEndDate: '2024-02-17',
      status: 'Approved'
    }
]